<?php

namespace ECommerceBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    public function FindOneByRefrence($refrence)
    {
        $query = $this->createQueryBuilder('p');
        $query->Where("p.refrence=:refrence")->setParameter('refrence',$refrence);

        return $query->GetQuery()->getResult();

    }

}
