Add_Product:
    path:     /admin/Add_Product
    defaults: { _controller: ECommerceBundle:Product:Add_Product }
next:
    path:     /admin/next
    defaults: { _controller: ECommerceBundle:Image:next }
im:
    path:     /admin/im
    defaults: { _controller: ECommerceBundle:Image:im }
remove_image:
    path:     /admin/remove_image
    defaults: { _controller: ECommerceBundle:Image:remove_image }


test:
    path:     /admin/test
    defaults: { _controller: ECommerceBundle:Product:test }


List_Product:
    path:     /admin/List_Product
    defaults: { _controller: ECommerceBundle:Product:List_Product }


Delete_Product:
    path:     /admin/Delete_Product/{id}
    defaults: { _controller: ECommerceBundle:Product:Delete_Product }

Modify_Product:
    path:     /admin/Modify_Product/{id}
    defaults: { _controller: ECommerceBundle:Product:Modify_Product }

modifier_next:
    path:     /admin/modifier_next
    defaults: { _controller: ECommerceBundle:Image:modifier_next }

List_Product_Front:
    path:     /List_Product_Front/{category}
    defaults: { _controller: ECommerceBundle:Product:List_Product_Front }

Single_Product_Front:
    path:     /Single_Product_Front/{refrence}
    defaults: { _controller: ECommerceBundle:Product:Single_Product_Front }



Add_Cart:
    path:     /Add_Cart
    defaults: { _controller: ECommerceBundle:Cart:Add_Cart }
Cart:
    path:     /Cart
    defaults: { _controller: ECommerceBundle:Cart:Cart }
delete_article:
    path:     /delete_article/{id_article}
    defaults: { _controller: ECommerceBundle:Cart:delete_article }

return_to_products:
    path:     /return_to_products
    defaults: { _controller: ECommerceBundle:Cart:return_to_products }


empty_cart:
    path:     /empty_cart
    defaults: { _controller: ECommerceBundle:Cart:empty_cart }

checkout_confirm:
    path:     /checkout_confirm
    defaults: { _controller: ECommerceBundle:Commande:checkout_confirm }

List_Commande:
    path:     /admin/List_Commande
    defaults: { _controller: ECommerceBundle:Commande:List_Commande }










